package com.opencray.llm

object LiteLlmMetadataKeys {
  const val RESPONSES_LINEAGE_ID: String = "responsesLineageId"
  const val VALIDATION_ENABLE_RESPONSES_CONTINUATION: String = "validationEnableResponsesContinuation"
  const val VALIDATION_ENABLE_RESPONSES_ASSISTANT_PHASES: String = "validationEnableResponsesAssistantPhases"
  const val VALIDATION_ENABLE_RESPONSES_CITATION_INCLUDE: String = "validationEnableResponsesCitationInclude"
  const val NATIVE_TOOL_CALL_REQUESTED: String = "nativeToolCallRequested"
  const val BUILTIN_WEB_SEARCH_REQUESTED: String = "builtinWebSearchRequested"
  const val BUILTIN_WEB_SEARCH_USED: String = "builtinWebSearchUsed"
  const val BUILTIN_WEB_SEARCH_OBSERVATIONS_JSON: String = "builtinWebSearchObservationsJson"
  const val BUILTIN_WEB_SEARCH_DIALECT: String = "builtinWebSearchDialect"
  const val PROVIDER_CITATION_COUNT: String = "providerCitationCount"
  const val PROVIDER_RESPONSE_SHAPE: String = "providerResponseShape"
  const val NATIVE_TOOL_CALL_OBSERVED: String = "nativeToolCallObserved"
  const val PARSED_TOOL_CALL_OBSERVED: String = "parsedToolCallObserved"
  const val FALLBACK_PARSER_ATTEMPTED: String = "fallbackParserAttempted"
  const val FALLBACK_PARSER_SUCCEEDED: String = "fallbackParserSucceeded"
  const val TOOL_CALL_EVENT_EMITTED: String = "toolCallEventEmitted"
  const val TOOL_RESULT_EVENT_EMITTED: String = "toolResultEventEmitted"
  const val LAST_SUCCESSFUL_TOOL_NAME: String = "lastSuccessfulToolName"
  const val PROVIDER_REASONING_OBSERVED: String = "providerReasoningObserved"
  const val PROVIDER_REASONING_TURN_COUNT: String = "providerReasoningTurnCount"
  const val PROVIDER_REASONING_CHARS: String = "providerReasoningChars"
  const val RESPONSES_COMMENTARY_PHASE_OBSERVED: String = "responsesCommentaryPhaseObserved"
  const val RESPONSES_FINAL_PHASE_OBSERVED: String = "responsesFinalPhaseObserved"
}
