package com.opencray.llm

object LiteLlmMetadataKeys {
  const val CONTEXT_CACHE_CONTRACT_VERSION: String = "contextCacheContractVersion"
  const val CONTEXT_CACHE_BREAK_REASON: String = "contextCacheBreakReason"
  const val CONTEXT_CACHE_STABLE_ANCHOR_HASH: String = "contextCacheStableAnchorHash"
  const val CONTEXT_CACHE_DURABLE_CONTEXT_HASH: String = "contextCacheDurableContextHash"
  const val CONTEXT_CACHE_DYNAMIC_CONTEXT_HASH: String = "contextCacheDynamicContextHash"
  const val CONTEXT_CACHE_FRONT_CONTEXT_ZONE_MASK: String = "contextCacheFrontContextZoneMask"
  const val CONTEXT_CACHE_FRONT_CONTEXT_MESSAGE_COUNT: String = "contextCacheFrontContextMessageCount"
  const val RESPONSES_LINEAGE_ID: String = "responsesLineageId"
  const val VALIDATION_ENABLE_RESPONSES_CONTINUATION: String = "validationEnableResponsesContinuation"
  const val VALIDATION_ENABLE_RESPONSES_REMOTE_COMPACTION: String = "validationEnableResponsesRemoteCompaction"
  const val VALIDATION_ENABLE_RESPONSES_ASSISTANT_PHASES: String = "validationEnableResponsesAssistantPhases"
  const val VALIDATION_ENABLE_RESPONSES_CITATION_INCLUDE: String = "validationEnableResponsesCitationInclude"
  const val NATIVE_TOOL_CALL_REQUESTED: String = "nativeToolCallRequested"
  const val BUILTIN_WEB_SEARCH_REQUESTED: String = "builtinWebSearchRequested"
  const val BUILTIN_WEB_SEARCH_USED: String = "builtinWebSearchUsed"
  const val BUILTIN_WEB_SEARCH_OBSERVATIONS_JSON: String = "builtinWebSearchObservationsJson"
  const val BUILTIN_WEB_SEARCH_DIALECT: String = "builtinWebSearchDialect"
  const val PROVIDER_CITATION_COUNT: String = "providerCitationCount"
  const val PROVIDER_RESPONSE_SHAPE: String = "providerResponseShape"
  const val NATIVE_TOOL_CALL_OBSERVED: String = "nativeToolCallObserved"
  const val PARSED_TOOL_CALL_OBSERVED: String = "parsedToolCallObserved"
  const val FALLBACK_PARSER_ATTEMPTED: String = "fallbackParserAttempted"
  const val FALLBACK_PARSER_SUCCEEDED: String = "fallbackParserSucceeded"
  const val TOOL_CALL_EVENT_EMITTED: String = "toolCallEventEmitted"
  const val TOOL_RESULT_EVENT_EMITTED: String = "toolResultEventEmitted"
  const val LAST_SUCCESSFUL_TOOL_NAME: String = "lastSuccessfulToolName"
  const val PROVIDER_REASONING_OBSERVED: String = "providerReasoningObserved"
  const val PROVIDER_REASONING_TURN_COUNT: String = "providerReasoningTurnCount"
  const val PROVIDER_REASONING_CHARS: String = "providerReasoningChars"
  const val PROVIDER_PROMPT_CACHE_USED: String = "providerPromptCacheUsed"
  const val PROVIDER_PROMPT_CACHE_READ_TOKENS: String = "providerPromptCacheReadTokens"
  const val PROVIDER_PROMPT_CACHE_WRITE_TOKENS: String = "providerPromptCacheWriteTokens"
  const val PROVIDER_PROMPT_CACHE_WRITE_5M_TOKENS: String = "providerPromptCacheWrite5mTokens"
  const val PROVIDER_PROMPT_CACHE_WRITE_1H_TOKENS: String = "providerPromptCacheWrite1hTokens"
  const val PROVIDER_PROMPT_CACHE_RETENTION: String = "providerPromptCacheRetention"
  const val PROVIDER_PROMPT_CACHE_KEY_PRESENT: String = "providerPromptCacheKeyPresent"
  const val PROVIDER_PROMPT_CACHE_CONTROL_PRESENT: String = "providerPromptCacheControlPresent"
  const val RESPONSES_COMMENTARY_PHASE_OBSERVED: String = "responsesCommentaryPhaseObserved"
  const val RESPONSES_FINAL_PHASE_OBSERVED: String = "responsesFinalPhaseObserved"
  const val RESPONSES_REMOTE_COMPACTION_SUPPORTED: String = "responsesRemoteCompactionSupported"
  const val RESPONSES_REMOTE_COMPACTION_REQUESTED: String = "responsesRemoteCompactionRequested"
  const val RESPONSES_REMOTE_COMPACTION_USED: String = "responsesRemoteCompactionUsed"
  const val RESPONSES_REMOTE_COMPACTION_TRIGGER_STAGE: String = "responsesRemoteCompactionTriggerStage"
  const val RESPONSES_REMOTE_COMPACTION_FALLBACK_REASON: String = "responsesRemoteCompactionFallbackReason"
  const val RESPONSES_REMOTE_COMPACTION_OUTPUT_ITEM_COUNT: String = "responsesRemoteCompactionOutputItemCount"
  const val RESPONSES_REMOTE_COMPACTION_ITEM_COUNT: String = "responsesRemoteCompactionItemCount"
  const val RESPONSES_REMOTE_COMPACTION_ENCRYPTED_CONTENT_COUNT: String =
    "responsesRemoteCompactionEncryptedContentCount"
}
