package com.opencray.app

internal data class HostRuntimeStrings(
  val localeTag: String,
  val shellHostLabel: String,
  val shellHostSummary: String,
  val chatScreenTitle: String,
  val chatModeLabel: String,
  val chatModeSafeLabel: String = "SAFE",
  val chatModeDeveloperLabel: String = "DEV",
  val chatSessionButtonLabel: String,
  val chatRecentSessionsEyebrow: String,
  val chatRecentSessionsTitle: String,
  val chatNewSessionLabel: String,
  val chatDefaultSessionTitle: String,
  val chatMessagesBadge: (Int) -> String,
  val chatSummaryReplyInProgress: String,
  val chatSummaryOnDevicePreparing: String = "Preparing the on-device model.",
  val chatSummaryAwaitingDirection: String = "Waiting for your next instruction.",
  val chatSummarySupplementRecorded: String = "Recorded. This will be applied to the current run when it reaches the next safe checkpoint.",
  val chatSummaryApprovalFollowUpRecorded: String = "Recorded. The current run is waiting for approval, so this message will be handled after that decision.",
  val chatSummaryStartNewSession: String,
  val chatSummaryRestored: String,
  val skillInstalled: (String) -> String,
  val skillRemoved: (String) -> String,
  val skillsReloaded: String,
  val composerPlaceholder: String,
  val chatMessageOnDevicePreparing: String = "Preparing on-device model",
  val composerRejectedPlaceholder: String,
  val agentThinking: String,
  val agentCancelled: String,
  val agentMissingLlm: String,
  val agentEmptyAnswer: String,
  val agentFailed: (String) -> String,
  val agentAttachmentSaveFailed: (String) -> String = { detail -> "Attachment could not be saved: $detail" },
  val agentInternalPayloadHidden: String = "The agent produced an internal tool payload instead of a user-facing reply.",
  val chatSummaryApprovalRequired: String = "Approval required before the agent can continue.",
  val chatApprovalRequiredTitle: String = "Approval required",
  val chatHighRiskApprovalRequiredTitle: String = "High-risk approval required",
  val chatHighRiskApprovalRequiredBody: String = "High-risk approval required. Review this request carefully before approving.",
  val chatApprovalApproveLabel: String = "Approve",
  val chatApprovalApproveForSessionLabel: String = "Allow session",
  val chatApprovalRejectLabel: String = "Reject",
  val chatApprovalApproved: String = "Approval granted. The agent is resuming.",
  val chatApprovalApprovedForSession: String = "Approval granted for this session. The agent is resuming.",
  val chatApprovalRejected: String = "Approval rejected. The requested action was not run.",
)
