package com.opencray.app

import com.opencray.app.facade.llm.LlmConfigSnapshot
import com.opencray.app.facade.llm.OnDeviceLlmModelOptionSnapshot
import com.opencray.app.facade.llm.LlmProviderOptionSnapshot
import com.opencray.app.facade.llm.LlmValidationResult
import com.opencray.app.facade.llm.SaveCustomLlmProviderRequest
import com.opencray.app.facade.llm.SaveLlmConfigRequest
import com.opencray.app.facade.llm.ValidateLlmConfigRequest

internal fun saveLlmConfigRequest(
  enabled: Boolean,
  streamingEnabled: Boolean?,
  providerMode: String,
  providerId: String,
  selectedProviderOptionId: String,
  protocol: String,
  providerName: String,
  providerNotes: String,
  baseUrl: String,
  apiKey: String,
  model: String,
  reasoningEffort: String,
  systemPrompt: String,
  openAiPromptCacheKeyStrategy: String?,
  openAiPromptCacheRetention: String?,
  anthropicPromptCachingEnabled: Boolean?,
  anthropicPromptCacheTtl: String?,
  contextBudgetPreset: String?,
  contextBudgetReservedOutputTokens: Int?,
  contextBudgetSafetyMarginTokens: Int?,
  contextBudgetEffectiveInputPercent: Double?,
  selectedOnDeviceModelId: String,
  onDeviceMaxContextWindow: Int,
  onDeviceMaxTokens: Int,
  onDeviceTopK: Int,
  onDeviceTopP: Double,
  onDeviceTemperature: Double,
  onDeviceAccelerator: String,
  onDeviceThinkingEnabled: Boolean,
  onDeviceLiteModeEnabled: Boolean,
  contextWindowTokensOverride: Int?,
): SaveLlmConfigRequest = SaveLlmConfigRequest(
  enabled = enabled,
  streamingEnabled = streamingEnabled,
  providerMode = providerMode,
  providerId = providerId,
  selectedProviderOptionId = selectedProviderOptionId,
  protocol = protocol,
  providerName = providerName,
  providerNotes = providerNotes,
  baseUrl = baseUrl,
  apiKey = apiKey,
  model = model,
  reasoningEffort = reasoningEffort,
  systemPrompt = systemPrompt,
  openAiPromptCacheKeyStrategy = openAiPromptCacheKeyStrategy,
  openAiPromptCacheRetention = openAiPromptCacheRetention,
  anthropicPromptCachingEnabled = anthropicPromptCachingEnabled,
  anthropicPromptCacheTtl = anthropicPromptCacheTtl,
  contextBudgetPreset = contextBudgetPreset,
  contextBudgetReservedOutputTokens = contextBudgetReservedOutputTokens,
  contextBudgetSafetyMarginTokens = contextBudgetSafetyMarginTokens,
  contextBudgetEffectiveInputPercent = contextBudgetEffectiveInputPercent,
  selectedOnDeviceModelId = selectedOnDeviceModelId,
  onDeviceMaxContextWindow = onDeviceMaxContextWindow,
  onDeviceMaxTokens = onDeviceMaxTokens,
  onDeviceTopK = onDeviceTopK,
  onDeviceTopP = onDeviceTopP,
  onDeviceTemperature = onDeviceTemperature,
  onDeviceAccelerator = onDeviceAccelerator,
  onDeviceThinkingEnabled = onDeviceThinkingEnabled,
  onDeviceLiteModeEnabled = onDeviceLiteModeEnabled,
  contextWindowTokensOverride = contextWindowTokensOverride,
)

internal fun saveCustomLlmProviderRequest(
  selectedProviderOptionId: String,
  streamingEnabled: Boolean?,
  protocol: String,
  providerName: String,
  providerNotes: String,
  baseUrl: String,
  apiKey: String,
  model: String,
  reasoningEffort: String,
  systemPrompt: String,
  openAiPromptCacheKeyStrategy: String?,
  openAiPromptCacheRetention: String?,
  anthropicPromptCachingEnabled: Boolean?,
  anthropicPromptCacheTtl: String?,
  contextBudgetPreset: String?,
  contextBudgetReservedOutputTokens: Int?,
  contextBudgetSafetyMarginTokens: Int?,
  contextBudgetEffectiveInputPercent: Double?,
  contextWindowTokensOverride: Int?,
): SaveCustomLlmProviderRequest = SaveCustomLlmProviderRequest(
  selectedProviderOptionId = selectedProviderOptionId,
  streamingEnabled = streamingEnabled,
  protocol = protocol,
  providerName = providerName,
  providerNotes = providerNotes,
  baseUrl = baseUrl,
  apiKey = apiKey,
  model = model,
  reasoningEffort = reasoningEffort,
  systemPrompt = systemPrompt,
  openAiPromptCacheKeyStrategy = openAiPromptCacheKeyStrategy
    ?: LlmSettingsState.DEFAULT_OPENAI_PROMPT_CACHE_KEY_STRATEGY,
  openAiPromptCacheRetention = openAiPromptCacheRetention
    ?: LlmSettingsState.DEFAULT_OPENAI_PROMPT_CACHE_RETENTION,
  anthropicPromptCachingEnabled = anthropicPromptCachingEnabled
    ?: LlmSettingsState.DEFAULT_ANTHROPIC_PROMPT_CACHING_ENABLED,
  anthropicPromptCacheTtl = anthropicPromptCacheTtl
    ?: LlmSettingsState.DEFAULT_ANTHROPIC_PROMPT_CACHE_TTL,
  contextBudgetPreset = contextBudgetPreset,
  contextBudgetReservedOutputTokens = contextBudgetReservedOutputTokens,
  contextBudgetSafetyMarginTokens = contextBudgetSafetyMarginTokens,
  contextBudgetEffectiveInputPercent = contextBudgetEffectiveInputPercent,
  contextWindowTokensOverride = contextWindowTokensOverride,
)

internal fun validateLlmConfigRequest(
  providerId: String,
  protocol: String,
  baseUrl: String,
  apiKey: String,
  model: String,
  reasoningEffort: String,
  contextWindowTokensOverride: Int?,
): ValidateLlmConfigRequest = ValidateLlmConfigRequest(
  providerId = providerId,
  protocol = protocol,
  baseUrl = baseUrl,
  apiKey = apiKey,
  model = model,
  reasoningEffort = reasoningEffort,
  contextWindowTokensOverride = contextWindowTokensOverride,
)

internal fun LlmConfigSnapshot.toGatewayMap(): Map<String, Any?> = mapOf(
  "localeTag" to localeTag,
  "enabled" to enabled,
  "streamingEnabled" to streamingEnabled,
  "providerMode" to providerMode,
  "providerId" to providerId,
  "selectedProviderOptionId" to selectedProviderOptionId,
  "protocol" to protocol,
  "providerOptions" to providerOptions.map { option -> option.toGatewayMap() },
  "providerName" to providerName,
  "providerNotes" to providerNotes,
  "baseUrl" to baseUrl,
  "apiKey" to apiKey,
  "model" to model,
  "reasoningEffort" to reasoningEffort,
  "systemPrompt" to systemPrompt,
  "openAiPromptCacheKeyStrategy" to openAiPromptCacheKeyStrategy,
  "openAiPromptCacheRetention" to openAiPromptCacheRetention,
  "anthropicPromptCachingEnabled" to anthropicPromptCachingEnabled,
  "anthropicPromptCacheTtl" to anthropicPromptCacheTtl,
  "contextBudgetPreset" to contextBudgetPreset,
  "contextBudgetReservedOutputTokens" to contextBudgetReservedOutputTokens,
  "contextBudgetSafetyMarginTokens" to contextBudgetSafetyMarginTokens,
  "contextBudgetEffectiveInputPercent" to contextBudgetEffectiveInputPercent,
  "manualContextWindowTokens" to manualContextWindowTokens,
  "resolvedContextWindowTokens" to resolvedContextWindowTokens,
  "onDeviceModels" to onDeviceModels.map { option -> option.toGatewayMap() },
  "selectedOnDeviceModelId" to selectedOnDeviceModelId,
  "onDeviceMaxContextWindow" to onDeviceMaxContextWindow,
  "onDeviceMaxTokens" to onDeviceMaxTokens,
  "onDeviceTopK" to onDeviceTopK,
  "onDeviceTopP" to onDeviceTopP,
  "onDeviceTemperature" to onDeviceTemperature,
  "onDeviceAccelerator" to onDeviceAccelerator,
  "onDeviceThinkingEnabled" to onDeviceThinkingEnabled,
  "onDeviceLiteModeEnabled" to onDeviceLiteModeEnabled,
  "helperText" to helperText,
  "agentCapability" to agentCapability.toGatewayMap(),
)

internal fun LlmValidationResult.toGatewayMap(): Map<String, Any?> = mapOf(
  "isSuccess" to isSuccess,
  "message" to message,
  "agentCapability" to agentCapability?.toGatewayMap(),
)

private fun LlmProviderOptionSnapshot.toGatewayMap(): Map<String, Any?> = mapOf(
  "id" to id,
  "providerId" to providerId,
  "title" to title,
  "subtitle" to subtitle,
  "defaultBaseUrl" to defaultBaseUrl,
  "defaultModel" to defaultModel,
  "protocol" to protocol,
  "apiKey" to apiKey,
  "isCustom" to isCustom,
)

private fun OnDeviceLlmModelOptionSnapshot.toGatewayMap(): Map<String, Any?> = mapOf(
  "id" to id,
  "title" to title,
  "subtitle" to subtitle,
  "sizeLabel" to sizeLabel,
  "fileSizeBytes" to fileSizeBytes,
  "installState" to installState,
  "downloadState" to installState,
  "downloadedBytes" to downloadedBytes,
  "downloadBytesPerSecond" to downloadBytesPerSecond,
  "sha256Verified" to sha256Verified,
  "isSelected" to isSelected,
  "lastError" to lastError,
)

private fun LlmAgentCapabilitySnapshot.toGatewayMap(): Map<String, Any?> = mapOf(
  "routeFingerprint" to routeFingerprint,
  "verifiedAtEpochMs" to verifiedAtEpochMs,
  "wasVerified" to wasVerified,
  "contextWindowTokens" to contextWindowTokens,
  "visionInputSupported" to visionInputSupported,
  "nativeToolCallingAvailable" to nativeToolCallingAvailable,
  "toolChoiceSupported" to toolChoiceSupported,
  "parallelToolCallsSupported" to parallelToolCallsSupported,
  "strictToolSchemaSupported" to strictToolSchemaSupported,
  "responsesContinuationSupported" to responsesContinuationSupported,
  "builtinWebSearchSupported" to builtinWebSearchSupported,
  "assistantPhaseSupported" to assistantPhaseSupported,
  "citationIncludeSupported" to citationIncludeSupported,
)
