package com.opencray.runtime.policy

import com.opencray.policy.PolicyToolClass
import org.junit.Assert.assertEquals
import org.junit.Test

class ToolCapabilityClassifierTest {
  private val classifier = ToolCapabilityClassifier()

  @Test
  fun classifiesExecutionToolsConsistently() {
    assertEquals(PolicyToolClass.EXECUTE_COMMAND, classifier.classifyPolicyToolClass("Bash"))
    assertEquals(PolicyToolClass.EXECUTE_COMMAND, classifier.classifyPolicyToolClass("command_exec"))
    assertEquals(PolicyToolClass.EXECUTE_COMMAND, classifier.classifyPolicyToolClass("python_exec"))
    assertEquals(PolicyToolClass.EXECUTE_COMMAND, classifier.classifyPolicyToolClass("ProcessStart"))
    assertEquals(PolicyToolClass.EXECUTE_COMMAND, classifier.classifyPolicyToolClass("ProcessTerminate"))
    assertEquals("execute_command", classifier.classifyCapabilityKind("Bash"))
    assertEquals("execute_command", classifier.classifyCapabilityKind("ProcessStart"))
    assertEquals("process_control", classifier.classifyCapabilityKind("ProcessTerminate"))
    assertEquals("delegate_task", classifier.classifyCapabilityKind("Task"))
    assertEquals("delegate_task", classifier.classifyCapabilityKind("list_subagents"))
  }

  @Test
  fun classifiesFileAndNetworkToolsConsistently() {
    assertEquals(PolicyToolClass.WRITE_FILE, classifier.classifyPolicyToolClass("Write"))
    assertEquals(PolicyToolClass.WRITE_FILE, classifier.classifyPolicyToolClass("Edit"))
    assertEquals(PolicyToolClass.WRITE_FILE, classifier.classifyPolicyToolClass("import_chat_attachment"))
    assertEquals(PolicyToolClass.WRITE_FILE, classifier.classifyPolicyToolClass("PublishMediaArtifact"))
    assertEquals(PolicyToolClass.WRITE_FILE, classifier.classifyPolicyToolClass("ScheduledTaskCreate"))
    assertEquals(PolicyToolClass.WRITE_FILE, classifier.classifyPolicyToolClass("ScheduledTaskUpdate"))
    assertEquals(PolicyToolClass.WRITE_FILE, classifier.classifyPolicyToolClass("ScheduledTaskDelete"))
    assertEquals(PolicyToolClass.READ_FILE, classifier.classifyPolicyToolClass("ScheduledTaskList"))
    assertEquals(PolicyToolClass.READ_FILE, classifier.classifyPolicyToolClass("ScheduledTaskGet"))
    assertEquals(PolicyToolClass.MOVE_FILE, classifier.classifyPolicyToolClass("workspace_move_file"))
    assertEquals(PolicyToolClass.DELETE_FILE, classifier.classifyPolicyToolClass("workspace_delete_file"))
    assertEquals(PolicyToolClass.NETWORK_ACCESS, classifier.classifyPolicyToolClass("WebFetch"))
    assertEquals(PolicyToolClass.NETWORK_ACCESS, classifier.classifyPolicyToolClass("GenerateImage"))
    assertEquals(PolicyToolClass.NETWORK_ACCESS, classifier.classifyPolicyToolClass("SynthesizeSpeech"))
    assertEquals(PolicyToolClass.NETWORK_ACCESS, classifier.classifyPolicyToolClass("sandbox_preview_open"))
    assertEquals(PolicyToolClass.NETWORK_ACCESS, classifier.classifyPolicyToolClass("sandbox_session_close"))
    assertEquals(PolicyToolClass.NETWORK_ACCESS, classifier.classifyPolicyToolClass("sandbox_session_info"))
    assertEquals(PolicyToolClass.READ_FILE, classifier.classifyPolicyToolClass("Read"))
    assertEquals(PolicyToolClass.READ_FILE, classifier.classifyPolicyToolClass("search_workspace_document"))
    assertEquals(PolicyToolClass.READ_FILE, classifier.classifyPolicyToolClass("inspect_workspace_package"))
    assertEquals(PolicyToolClass.READ_FILE, classifier.classifyPolicyToolClass("view_workspace_document"))
    assertEquals(PolicyToolClass.READ_FILE, classifier.classifyPolicyToolClass("view_workspace_image"))
    assertEquals(PolicyToolClass.READ_FILE, classifier.classifyPolicyToolClass("view_workspace_pdf"))
    assertEquals(PolicyToolClass.READ_FILE, classifier.classifyPolicyToolClass("session_search"))
    assertEquals(PolicyToolClass.READ_FILE, classifier.classifyPolicyToolClass("session_get"))
    assertEquals(PolicyToolClass.READ_FILE, classifier.classifyPolicyToolClass("past_session_search"))
    assertEquals(PolicyToolClass.READ_FILE, classifier.classifyPolicyToolClass("past_session_get"))
    assertEquals(PolicyToolClass.WRITE_FILE, classifier.classifyPolicyToolClass("extract_workspace_package"))
    assertEquals(PolicyToolClass.READ_FILE, classifier.classifyPolicyToolClass("Task"))
    assertEquals(PolicyToolClass.READ_FILE, classifier.classifyPolicyToolClass("list_subagents"))
    assertEquals("write_file", classifier.classifyCapabilityKind("Write"))
    assertEquals("write_file", classifier.classifyCapabilityKind("import_chat_attachment"))
    assertEquals("write_file", classifier.classifyCapabilityKind("PublishMediaArtifact"))
    assertEquals("move_file", classifier.classifyCapabilityKind("workspace_move_file"))
    assertEquals("delete_file", classifier.classifyCapabilityKind("workspace_delete_file"))
    assertEquals("network_access", classifier.classifyCapabilityKind("WebFetch"))
    assertEquals("network_access", classifier.classifyCapabilityKind("GenerateImage"))
    assertEquals("network_access", classifier.classifyCapabilityKind("SynthesizeSpeech"))
    assertEquals("network_access", classifier.classifyCapabilityKind("sandbox_preview_open"))
    assertEquals("network_access", classifier.classifyCapabilityKind("sandbox_session_close"))
    assertEquals("network_access", classifier.classifyCapabilityKind("sandbox_session_info"))
    assertEquals("read_file", classifier.classifyCapabilityKind("Read"))
    assertEquals("read_file", classifier.classifyCapabilityKind("search_workspace_document"))
    assertEquals("read_file", classifier.classifyCapabilityKind("inspect_workspace_package"))
    assertEquals("read_file", classifier.classifyCapabilityKind("view_workspace_document"))
    assertEquals("read_file", classifier.classifyCapabilityKind("view_workspace_image"))
    assertEquals("read_file", classifier.classifyCapabilityKind("view_workspace_pdf"))
    assertEquals("read_memory", classifier.classifyCapabilityKind("session_search"))
    assertEquals("read_memory", classifier.classifyCapabilityKind("session_get"))
    assertEquals("read_memory", classifier.classifyCapabilityKind("past_session_search"))
    assertEquals("read_memory", classifier.classifyCapabilityKind("past_session_get"))
    assertEquals("write_file", classifier.classifyCapabilityKind("extract_workspace_package"))
    assertEquals("read_python_runtime", classifier.classifyCapabilityKind("python_runtime_manifest"))
    assertEquals("todo_management", classifier.classifyCapabilityKind("TodoWrite"))
    assertEquals("schedule_task", classifier.classifyCapabilityKind("ScheduledTaskCreate"))
    assertEquals("schedule_task", classifier.classifyCapabilityKind("ScheduledTaskList"))
    assertEquals("schedule_task", classifier.classifyCapabilityKind("ScheduledTaskGet"))
    assertEquals("schedule_task", classifier.classifyCapabilityKind("ScheduledTaskUpdate"))
    assertEquals("schedule_task", classifier.classifyCapabilityKind("ScheduledTaskDelete"))
  }
}
